### ISSUE TITLE
Testing objects/repo

### ISSUE THREAD

**Issue by magik6k** [ipfs/go-ipld-git#3]
It would be useful to have the ability to provide a custom git repository for tests, though I don't know how it should be created, current ideas(discussed with @Kubuxu) include:
* Providing static zip/tar archive with git repo which would be then unzipped in go test
  * This introduces some mess into test code
  * It's a bit harder to update tests that way
* Have a script that would generate the repo
  * Easier to change/add test cases
  * Requires GIT on CI

Though I'm not sure which is best, I'm tilting toward the archive way.
cc @whyrusleeping

**Comment by whyrusleeping** [comment]
I think an archive would be fine, it does make updating tests harder, but since git itself isnt likely to change often, i don't think we have to worry too much about that difficulty
