### ISSUE TITLE
Register a DecodeBlockFunc with go-ipld-format

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipld-git#4]
go-ipld-format 0.4.8 now supports [decoding](https://godoc.org/github.com/ipfs/go-ipld-format#Decode) any arbitrary [`Block`](https://godoc.org/github.com/ipfs/go-block-format#Block) into an IPLD [`Node`](https://godoc.org/github.com/ipfs/go-ipld-format#Node) if there's a registered [`DecodeBlockFunc`](https://godoc.org/github.com/ipfs/go-ipld-format#DecodeBlockFunc) for the block's codec in [`DefaultBlockDecoder`](https://godoc.org/github.com/ipfs/go-ipld-format#BlockDecoder). This package should implement and register such a function.

**Comment by whyrusleeping** [comment]
completed in #2
