### ISSUE TITLE
Remove GX CI check

### ISSUE THREAD

**Issue by willscott** [ipfs/go-ipld-git#43]
CI script with GX are failing. Any Objection to remove?

ref: https://travis-ci.com/github/ipfs/go-ipld-git/jobs/482100735#L251-L257

line in question:
https://github.com/ipfs/go-ipld-git/blob/c7803219b4c45ad93ac846213165cfdd84183e4d/.travis.yml#L13

**Comment by rvagg** [comment]
none, rip it out
