### ISSUE TITLE
Create IPLD-Prime codec that can surplant the ipld-format functionality in this repo

### ISSUE THREAD

**Issue by willscott** [ipfs/go-ipld-git#45]
Currently, this implements an ipld-format view of blocks containing git data.
We need an [ipld-prime](https://github.com/ipld/go-ipld-prime) view of the same data if we want integrate it into IPFS

**Comment by drgomesp** [comment]
Is there any update on this? Not sure if such implementation can be found anywhere else.

**Comment by aschmahmann** [comment]
@drgomesp I don't understand the question as indicated two lines above this was done in #46 and closed over a year ago

**Comment by drgomesp** [comment]
My bad @aschmahmann , I didn't do my research properly.
The question comes from my current testing with this library by experimenting with a local filesystem store implementation (`fsstore.Store`).

**Comment by aschmahmann** [comment]
No problem. If you're finding yourself having issues check out https://docs.ipfs.tech/community/ and follow the links to ask around on the forums or chat channels.
