### ISSUE TITLE
Cache the cid

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipld-git#6]
go-ipfs and friends make no attempt to cache Node CIDs and will call `Cid()` repeatedly as-needed. Therefore, calling `Cid()` *should not* recompute the CID each time. Instead, it should either be cached on when first computed (preferably, when the node is first decoded).

Furthermore, the raw data should be kept around if possible so that calling `RawData()` is free. I don't expect this to tie up *that* much memory.

**Comment by lgierth** [comment]
> Furthermore, the raw data should be kept around if possible so that calling RawData() is free. I don't expect this to tie up that much memory.

You can have different CID implementations for different performance use cases, just in case it does tie up too much memory

**Comment by Stebalien** [comment]
**Cache CID**
* [ ] Blob

**Cache RawData**
* [ ] Commit
* [ ] Tag
* [ ] RawData

**Comment by Stebalien** [comment]
> You can have different CID implementations for different performance use cases, just in case it does tie up too much memory

Different CID implementations? A node's CID should never change (and CIDs are concrete types...).

**Comment by lgierth** [comment]
> and CIDs are concrete types...

Ah right
