### ISSUE TITLE
Size() shouldn't return a constant.

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipld-git#7]
So, `Node.Size()` means different things in different places (https://github.com/ipfs/go-ipld-format/issues/12). However, returning arbitrary constants (13, 42, etc...) as we're doing here is, unambiguously, wrong...

I know this is currently "not implemented" but this fact should probably be recorded in an issue so we can make sure to fix this when we actually decide on the semantics of `Node.Size()`.

**Comment by sameer** [comment]
This can be partially fixed after #28, since the raw data is stored after the first call to `RawData()`.
